KP-11496 Fix Airflow extras installing too new paramiko
Some of the extras apparently had paramiko requirements, as despite the
constraint file specifying `paramiko==3.5.1`, we actually had 5.0.0
installed:
```
ubuntu@harvester-small-test:~$ pip freeze | grep paramiko
paramiko==5.0.0
```
which caused errors:
```
Broken DAG: [/home/ubuntu/airflow/dags/download_single_binding.py]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/ssh/hooks/ssh.py", line 45, in <module>
    class SSHHook(BaseHook):
  File "/usr/local/lib/python3.10/dist-packages/airflow/providers/ssh/hooks/ssh.py", line 85, in SSHHook
    paramiko.DSSKey,
AttributeError: module 'paramiko' has no attribute 'DSSKey'
```

Separately installing the potentially problematic extras precents this
problem.